/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface BuiButton {
    /**
    * Extend the button the full width of the container
    */
    'block': boolean;
    /**
    * Whether the button is disabled
    */
    'disabled': boolean;
    /**
    * Link href
    */
    'href': string;
    /**
    * Display as outline button
    */
    'outline': boolean;
  }
  interface BuiButtonAttributes extends StencilHTMLAttributes {
    /**
    * Extend the button the full width of the container
    */
    'block'?: boolean;
    /**
    * Whether the button is disabled
    */
    'disabled'?: boolean;
    /**
    * Link href
    */
    'href'?: string;
    /**
    * Display as outline button
    */
    'outline'?: boolean;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BuiButton': Components.BuiButton;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'bui-button': Components.BuiButtonAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLBuiButtonElement extends Components.BuiButton, HTMLStencilElement {}
  var HTMLBuiButtonElement: {
    prototype: HTMLBuiButtonElement;
    new (): HTMLBuiButtonElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'bui-button': HTMLBuiButtonElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'bui-button': HTMLBuiButtonElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
